# font
font_family JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
italic_font      auto
font_size        18

#split windows
window_margin_width 5
single_window_margin_width 10
window_border_width 1.5pt
enable_layouts Tall, *
# active_border_color #7FFF00

#background
#background_image ~/Pictures/Backgrounds/Bloodbath.png
background_image_layout scaled
background_tint 1
background_tint_gaps -10
background_opacity 0.8
dynamic_background_opacity 1
confirm_os_window_close 0
background_blur 1

#tab
tab_bar_style fade

#cursor
cursor_shape block
shell_integration no-cursor
cursor_blink_interval 0
cursor_trail 150
cursor_trail_decay 0.05 0.25
cursor_trail_start_threshold 1

#scroll bar
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

#other
sync_to_monitor no

#theme
include current-theme.conf
